# Étape 1 : build l'app Go
FROM golang:1.21 as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o messaging-app ./cmd/messaging-app

# Étape 2 : image minimale pour exécuter
FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/messaging-app .

EXPOSE 8080

CMD ["./messaging-app"]

